"""
Approvals Management Page

Minimal UI to view and act on approval JSON files created by agents.
This page writes decisions back to `approvals/*.json` so `hitl.review_interface.WebReviewer`
(notifier) will detect changes and continue the approval workflow.

Usage: open in the Streamlit app after logging in.
"""

import os
import streamlit as st
import json
from pathlib import Path
from datetime import datetime

st.set_page_config(page_title="Approvals", page_icon="📝", layout="wide")

# In test mode we auto-authenticate to make automated UI tests easier.
if os.environ.get("TESTING") in ("1", "true", "True"):
    st.session_state.setdefault("authentication_status", True)
    st.session_state.setdefault("username", "test_user")

# Require login
if not st.session_state.get("authentication_status"):
    st.warning("⚠️ Please login to access approvals")
    st.stop()

# Allow tests to override the approvals directory via env var
approvals_dir = Path(os.environ.get("APPROVALS_DIR", "approvals"))
approvals_dir.mkdir(exist_ok=True)

st.title("📝 Approvals Management")
st.markdown("Review and approve/reject pending approval requests generated by agents.")

files = sorted(approvals_dir.glob("*.json"))

if not files:
    st.info("No approval requests found in the `approvals/` directory.")
    st.stop()

cols = st.columns([3, 1])
with cols[0]:
    selected = st.selectbox("Select approval file", [f.name for f in files])
with cols[1]:
    st.write("\n")
    if st.button("Refresh"):
        st.experimental_rerun()

file_path = approvals_dir / selected

try:
    with open(file_path, "r", encoding="utf8") as fh:
        data = json.load(fh)
except Exception as e:
    st.error(f"Failed to load {selected}: {e}")
    st.stop()

# Show metadata and current status
st.subheader("Approval Summary")
col1, col2, col3 = st.columns(3)
with col1:
    st.markdown(f"**ID:** `{data.get('id', selected)}`")
    st.markdown(f"**Type:** `{data.get('approval_type', data.get('approval_type','N/A'))}`")
with col2:
    st.markdown(f"**Item:** `{data.get('item_id', 'N/A')}`")
    st.markdown(f"**Requested:** `{data.get('requested_at', 'N/A')}`")
with col3:
    st.markdown(f"**Status:** `{data.get('status', 'PENDING')}`")
    st.markdown(f"**Approver:** `{data.get('approved_by', '')}`")

st.markdown("---")

st.subheader("Item Data")
st.json(data.get("item_data", data))

st.markdown("---")

st.subheader("Actions")

action_col1, action_col2, action_col3 = st.columns([1,1,2])
username = st.session_state.get("username", "web_user")

with action_col1:
    if st.button("Approve"):
        data["status"] = "APPROVED"
        data["approved_by"] = username
        data["approved_at"] = datetime.utcnow().isoformat()
        # optional comments field
        data.setdefault("comments", "Approved via Streamlit UI")
        with open(file_path, "w", encoding="utf8") as fh:
            json.dump(data, fh, indent=2)
        st.success("Approval saved.")
        st.experimental_rerun()

with action_col2:
    if st.button("Reject"):
        data["status"] = "REJECTED"
        data["approved_by"] = username
        data["rejection_reason"] = st.text_input("Rejection reason", value="Rejected via Streamlit UI")
        data["rejected_at"] = datetime.utcnow().isoformat()
        with open(file_path, "w", encoding="utf8") as fh:
            json.dump(data, fh, indent=2)
        st.error("Rejection saved.")
        st.experimental_rerun()

with action_col3:
    with st.form("edit_form"):
        st.markdown("**Edit raw JSON** (make sure to preserve required fields)")
        edited = st.text_area("Edit JSON", value=json.dumps(data, indent=2), height=300)
        submitted = st.form_submit_button("Save JSON")
        if submitted:
            try:
                parsed = json.loads(edited)
                with open(file_path, "w", encoding="utf8") as fh:
                    json.dump(parsed, fh, indent=2)
                st.success("File updated.")
                st.experimental_rerun()
            except Exception as e:
                st.error(f"Failed to parse JSON: {e}")

st.markdown("---")
st.info("Notes: The WebReviewer polls these files; changing status to APPROVED/REJECTED/MODIFIED will allow agents to continue their HITL flow.")

# Test-only hooks: visible when TESTING env var is set. These provide stable, explicit
# buttons for automated tests to click (Playwright selectors can target the exact text).
if os.environ.get("TESTING") in ("1", "true", "True"):
    st.markdown("---")
    st.subheader("Test Hooks (TESTING mode)")
    st.markdown("These buttons are only visible when `TESTING=1` and perform the same actions as the main buttons.")

    if st.button("[TEST] Approve Hook"):
        # replicate approve behavior
        data["status"] = "APPROVED"
        data["approved_by"] = username
        data["approved_at"] = datetime.utcnow().isoformat()
        data.setdefault("comments", "Approved via Streamlit TEST hook")
        with open(file_path, "w", encoding="utf8") as fh:
            json.dump(data, fh, indent=2)
        st.success("Test approval saved.")
        st.experimental_rerun()

    if st.button("[TEST] Reject Hook"):
        data["status"] = "REJECTED"
        data["approved_by"] = username
        data["rejection_reason"] = "Rejected via Streamlit TEST hook"
        data["rejected_at"] = datetime.utcnow().isoformat()
        with open(file_path, "w", encoding="utf8") as fh:
            json.dump(data, fh, indent=2)
        st.error("Test rejection saved.")
        st.experimental_rerun()
